image: docker:latest
services:
- docker:dind

stages:
- build
- test
- release

variables:
  TEST_IMAGE : "$CI_REGISTRY_IMAGE"
  RELEASE_IMAGE : "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" 
#  TEST_IMAGE: gitlab.example.com:5555/sammy/hello_hapi:$CI_COMMIT_REF_NAME
#  RELEASE_IMAGE: gitlab.example.com:5555/sammy/hello_hapi:latest

before_script:
#  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab.example.com:5555
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
#    - docker build --pull -t $TEST_IMAGE .
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
#    - docker push $TEST_IMAGE    
    - docker push "$CI_REGISTRY_IMAGE"

test:
  stage: test
  script:
#    - docker pull $TEST_IMAGE
#    - docker run $TEST_IMAGE npm test

release:
  stage: release
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  only:
    - master
