version: "3"
services:
  web:
    image: mklauzo/drzewiec_www:ver2
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8085:80"
    networks:
      - webnet
networks:
  webnet:
